// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIL4nMg_U6IyEWXqww_tBRH8OMRLohmk',
    appId: '1:9956980467:android:51b56ac34dbf973e956986',
    messagingSenderId: '9956980467',
    projectId: 'vouse-4d2c0',
    storageBucket: 'vouse-4d2c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqkdZxFo5LHpHY6ycN85vAUDYDgKP_fl0',
    appId: '1:9956980467:ios:375772fc4ab8a9fe956986',
    messagingSenderId: '9956980467',
    projectId: 'vouse-4d2c0',
    storageBucket: 'vouse-4d2c0.firebasestorage.app',
    androidClientId: '9956980467-73sff6dhac0u5m9ano3ecfahipo46lsn.apps.googleusercontent.com',
    iosClientId: '9956980467-mp1j1i097gmkqta9k534n8k8d63uhfpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vouseFlutter',
  );

}